sonar.projectKey=cine-backend
sonar.projectName=Cine Backend
sonar.projectVersion=1.0

sonar.sources=app/src
sonar.tests=app/src
sonar.test.inclusions=**/__tests__/**/*.test.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts

sonar.javascript.lcov.reportPaths=app/coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=${env.SONAR_TOKEN}